server:
  port: 8087

spring:
  application:
    name: concierge-service

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:discovery-server}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:zipkin}:9411/api/v2/spans
