apiVersion: v1
kind: ConfigMap
metadata:
  name: starlight-config
  namespace: starlight-mesh
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_SERVER_URL: "http://discovery-server.starlight-mesh.svc.cluster.local:8761/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server.starlight-mesh.svc.cluster.local:8888"
  DB_HOST: "postgres.starlight-mesh.svc.cluster.local"
  DB_PORT: "5432"
  REDIS_HOST: "redis.starlight-mesh.svc.cluster.local"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq.starlight-mesh.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  ZIPKIN_ENDPOINT: "http://zipkin.starlight-mesh.svc.cluster.local:9411/api/v2/spans"
---
apiVersion: v1
kind: Secret
metadata:
  name: starlight-secrets
  namespace: starlight-mesh
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  JWT_SECRET: "StarlightStaysSuperSecretKeyForJwtValidation2026"
